[file]
[backends]
  [backends.backend-synology-dsm]
    [backends.backend-synology-dsm.servers]
      [backends.backend-synology-dsm.servers.server-synology-dsm-ext]
        url = "http://<LOCAL_SYNOLOGY_IP>:5000"
        weight = 0
[frontends]
  [frontends.frontend-synology-dsm]
    backend = "backend-synology-dsm"
    passHostHeader = true
    entrypoints = ["https"]
    [frontends.frontend-synology-dsm.routes]
      [frontends.frontend-synology-dsm.routes.route-synology-dsm-ext]
      rule = "Host:dsm.<YOUR.DOMAIN>.com"
